### ISSUE TITLE
Cobertura-formatted XML reports?

### ISSUE THREAD

**Issue by obuseme** [jonreid/XcodeCoverage#15]
First off - I just ran through your setup and have to say that this is phenomenal.  By far, the most easiest and quickest setup for measuring code coverage of iOS projects.  I was nervous when I found an outdated blog post referencing this project, but then when I came to GitHub and saw you are actively maintaining it, I was pumped.  Thank you

How can I modify this script to generate an XML report that may be consumed by Cobertura in order to better display the coverage stats in Jenkins?

**Comment by jonreid** [comment]
Just merged pull request https://github.com/jonreid/XcodeCoverage/pull/29 which adds Cobertura support
