### ISSUE TITLE
Bizzarre results on codecoverage

### ISSUE THREAD

**Issue by ignazioc** [jonreid/XcodeCoverage#16]
First of all, thanks for this script.
I tested this script with a sample project (here the source: https://github.com/ignazioc/SampleCodeCoverage) 
and the report shows 0% coverage on the unique sample class inside the project.

But when i use cover story on the same project it shows 100% coverage.

**Comment by jonreid** [comment]
Apologies for taking so long to notice this issue. It puzzled me, but I finally found it: SampleClass.m has a target membership of both the app and the tests, which is incorrect. Take it out of the tests.
