### ISSUE TITLE
The updated version fails for files using blocks

### ISSUE THREAD

**Issue by kunalbalani** [jonreid/XcodeCoverage#18]
I have 5408 files in my project and it shows only 4. 
geninfo: ERROR: GCOV failed for (build_artifacts)/(class_that_errored).gcda!

Here is detailed description of problem http://stackoverflow.com/questions/22343725/xcode-5-1-unit-test-coverage-analysis-fails-on-files-using-blocks

**Comment by jonreid** [comment]
Try the latest XcodeCoverage, which incorporates the fix described in your SO question, and uses the latest LCOV.
