### ISSUE TITLE
exportenv.sh always exports i386

### ISSUE THREAD

**Issue by lumaxis** [jonreid/XcodeCoverage#30]
I just noticed an issue when trying to run my tests against a 64bit simulator e.g. an iPhone 6 simulator.
Then the script always puts `i386` as `CURRENT_ARCH` into the `env.sh` file.
Might this be an issue I'm having with my build settings or does anyone know another way to fix this? Thanks!

**Comment by jonreid** [comment]
Hmm. Try the latest XcodeCoverage and do `getcov -v` for verbose.

**Comment by lumaxis** [comment]
Hi Jon, thanks for taking the time to reply.
I just retried this with the most recent version from `master` and still had the issue. This caused me to some more digging. The issue was: On the build configuration I was using for "Test" in my scheme, the "Build Active Archive Only" flag was set to `NO` which caused `i386` to always be exported as `CURRENT_ARCH` when doing a test build. After changing that, everything works fine now :+1:

**Comment by jonreid** [comment]
Great!
