### ISSUE TITLE
@implementation showing as not covered.

### ISSUE THREAD

**Issue by jonahneugass-ck** [jonreid/XcodeCoverage#31]
For some reason the @implementation line for this one class is showing as not being covered.

![lcov_-_coverage_info_-_classes_ckmdatamanager_m](https://cloud.githubusercontent.com/assets/9939088/5910413/bd0da6d0-a56e-11e4-9092-89e60085ff06.png)

**Comment by jonreid** [comment]
Yeah, I've seen that. No idea.
