### ISSUE TITLE
exportenv.sh is failing to create env.sh on a TeamCity CI Server

### ISSUE THREAD

**Issue by gregyoung07** [jonreid/XcodeCoverage#36]
I'm able to successfully run and build my project using a standard installation of XcodeCoverage on a local instance on my machine. 

However, our TeamCity CI Server (Mac Mini OSX 10.10 with Xcode) is unable to successfully execute the exportenv.sh script. This results in a null env.sh which then causes some additional libraries to fail (fabric io specifically) thus causing compile errors.

There really isn't much of an error being posted to console output either, it simply says
 
"[13:33:47]Step 2/6: export env.sh (Command Line)
[13:33:47][Step 2/6] Starting: /Library/TeamCity/buildAgent/temp/agentTmp/custom_script9004978931224840444
[13:33:47][Step 2/6] in directory: /Library/TeamCity/buildAgent/work/c611c1ea3bea1202
[13:33:47][Step 2/6] Process exited with code 1
[13:33:47][Step 2/6] Step export env.sh (Command Line) failed"

I've reviewed the actual script and I don't see any errors or mistakes, it also hasn't been modified. 

Is there anything that I should be calling/running before calling exportenv.sh I know there are a handful of build scripts in there. Any help is very much appreciated!

**Comment by jonreid** [comment]
env.sh is written to the XcodeCoverage directory. Can you find a way to check that TeamCity gives you write permission?
