### ISSUE TITLE
Using XcodeCoverage with sandboxed Mac Apps

### ISSUE THREAD

**Issue by iljaiwas** [jonreid/XcodeCoverage#37]
I'd like to generate coverage report for a sandboxed OS X file. This is a little tricky, because the running application cannot write covering coverage data to it's build directory.

I followed the instructions at https://developer.apple.com/library/ios/qa/qa1514/_index.html for sandboxed applications.
The .gcda files are now located in the sandboxed application's Document directory within its sandbox container. e.g. ~/Library/Containers/<bundle_id>/Data/Documents/Build/Intermediates/<app name>/........

The .o file and .gcno files are somewhere in Xcode's derived data directory. Any ideas how to handle this situation?

**Comment by jonreid** [comment]
Sorry, I have no experience with sandboxed Mac apps. Maybe try asking on StackOverflow?
