### ISSUE TITLE
No unit test coverage, but AppDeledate coverage

### ISSUE THREAD

**Issue by shirerom** [jonreid/XcodeCoverage#39]
I installed XcodeCoverage to my project like descriped in README.md. I tried pods and standard installation and had always the same effect:

- code coverage on every line which were executed by the app delegate before the unit tests started
- no code coverage on lines which were executed by the unit tests

I already asked Google but didn't get an answer that worked. I also tried the __gcov_flush() function,  but no effect neither.

I use Xcode6, iOS simulator 8.3 and 8.4.

Any ideas?

**Comment by jonreid** [comment]
Were you ever able to solve this?

**Comment by shirerom** [comment]
Nope, but I didn't put much effort into it since then.

**Comment by jonreid** [comment]
Maybe a fresh start will help :)
