### ISSUE TITLE
Is XcodeCoverage going to be updated to work with the LLVM-COV profdata file?

### ISSUE THREAD

**Issue by bixbarton** [jonreid/XcodeCoverage#42]
Since SDK 9 I am unable to use XcodeCoverage.

I cannot turn on INSTRUMENT_PROGRAM_FLOW to generate the GCOV files, as it causes my test run to fail. Lots of "cannot merge previous GCDA file: corrupt arc tag" entries in the console, and it then crashes in main.m showing BAD_ACCESS on the line calling UIApplicationMain.

I cannot turn INSTRUMENT_PROGRAM_FLOW on for the main target, but without it, I cannot generate GCDA files.

Is there a way to fix this, or do we need to wait till XcodeCoverage supports LLVM-COV profdata?

**Comment by jonreid** [comment]
XcodeCoverage simply builds on lcov. I don't have the bandwidth to parse the new data format myself.

**Comment by Panajev** [comment]
I was able to generate code coverage on our project which uses the iOS 9 SDK, but the lcov version in the current tagged release (which the pod references is wrong): https://github.com/jonreid/XcodeCoverage/issues/43.

**Comment by jonreid** [comment]
See if the latest release with lcov 1.12 helps.
