### ISSUE TITLE
Can you retag and update the pod to include lcov1.12?

### ISSUE THREAD

**Issue by Panajev** [jonreid/XcodeCoverage#43]
Hello Jon,
It would be helpful if the Pod allowed you to install the latest lcov release, but the last available tag is stuck at lcov 1.11. Could you retag and update and publish the podspec?

**Comment by Panajev** [comment]
The current podspec references the XcodeCoverage 1.2.2 which was tagged March 2015:
https://github.com/jonreid/XcodeCoverage/releases

![screenshot 2016-02-29 14 58 31](https://cloud.githubusercontent.com/assets/562991/13398204/34ec9ba0-def5-11e5-8257-fd3ae182cd3c.png)

**Comment by jonreid** [comment]
Done. Thanks for the nudge.

**Comment by Panajev** [comment]
Thank you, got my coverage back :).
