### ISSUE TITLE
Excluding Files From Coverage .xcodecoverageignore

### ISSUE THREAD

**Issue by amin234** [jonreid/XcodeCoverage#44]
where i can but my excluding paths there no files with this extension .xcodecoverageignore
to add ${SRCROOT}/TestedProject/Machine Files/*

**Comment by jonreid** [comment]
Create a new file called .xcodecoverageignore located wherever your SRCROOT is.

**Comment by amin234** [comment]
cat: ~/.xcodecoverageignore: No such file or directory

**Comment by jonreid** [comment]
Not in your home directory. In the same directory that contains your Xcode project. And you have to create it yourself if you want it. Note that it's not required.

**Comment by amin234** [comment]
no  it is required to exclude some file i created file named    ~/xocodeproject/exclude.xcodecoverageignore

**Comment by jonreid** [comment]
Let's start over. Can you describe what problem you're facing?
