### ISSUE TITLE
Code coverage in Xcode without tests (for manual run)

### ISSUE THREAD

**Issue by wangtao169447** [jonreid/XcodeCoverage#45]
Code Coverage is commonly used with tests in Xcode. I would like to use it for manually executed app. Can I do it, possibly with third-party tools?

For example: I build and launch the app on device, perform some actions with it and then look at code coverage results.

before Xcode7. The way we achieved this was, to set the "Instrument Program Flow" and "Generate Test Coverage files" flags to Yes, on your project, and later add a "flush" code somewhere inside you application, to write the coverage data files. This "flushing" part actually writes the coverage data files, which can be used later by other tools such as gcovr or lcov, to get your coverage data. Once you interact with the app, either manually or through automated tests, the coverage data gets written.

However, with Xcode7, looks like the coverage data is limited to only Xcode unit tests. I am still trying to figure out, if there is any way to gather the coverage data, by interacting with the application manually, or through automated tests.

Please let me know if you find something useful.

**Comment by jonreid** [comment]
I bet you can get the old behavior back by setting "Generate Legacy Test Coverage Files" or GCC_GENERATE_TEST_COVERAGE_FILES.

Of course, Apple may take that option away from us in the next Xcode for all we know.
