### ISSUE TITLE
Xcode 8 Support

### ISSUE THREAD

**Issue by Bupterambition** [jonreid/XcodeCoverage#48]
Hi, jonreid,I found the XcodeCoverage cannot work for Xcode 8GM

**Comment by hdu-rtt** [comment]
me too....

**Comment by Sidetalker** [comment]
+1 on this, was looking forward to trying out this tool!

**Comment by Bupterambition** [comment]
hi,Sidetalker,I just fix the bug;You can use the lastest Icov [https://github.com/linux-test-project/lcov/tree/master/bin ] just replace the XcodeCoverage/lcov-1.12/bin

**Comment by Sidetalker** [comment]
Awesome, thanks @Bupterambition!
