### ISSUE TITLE
Unexpected number of functions & Unexpected number of edges

### ISSUE THREAD

**Issue by Cyqlblgy** [jonreid/XcodeCoverage#52]
Hi,
   I really liked your tool to get html version coverage report, but I've been getting Unexpected number of edges and Unexpected number of functions errors when I tried to generate report for my unit test, also the xcodecoverageignore file is not working as expected, an sample is ${SRCROOT}/../../../../android/sdk/src/main/jni/source/sqlite3.c.
Please advise thanks.

**Comment by jonreid** [comment]
It's worked before, but now it's not? I don't have any knowledge of gcov internals, so I really can't help beyond normal advice: update, clean, regenerate.
