### ISSUE TITLE
How to set IGNORED

### ISSUE THREAD

**Issue by jeremyzj** [jonreid/XcodeCoverage#53]
How to set IGNORED

**Comment by jeremyzj** [comment]
I know

**Comment by diaojunxian** [comment]
@jeremyzj Hi，as I set the IGNORED file `.xcodecoverageignore `  in SRCROOT,  as the example
```
${SRCROOT}/Carthage/*
${SRCROOT}/Pods/*
```
but it can not work, why it hanpped ,can you help me?

**Comment by qyhongfan** [comment]
it can not work too
