### ISSUE TITLE
Swift support with xcode 9.4

### ISSUE THREAD

**Issue by parkasalfluke** [jonreid/XcodeCoverage#57]
HI Jon,

Background : We are using your XcodeCoverage report to generate html reports for our project which has a mix of ObjC and Swift Classes. ObjC works perfectly but XcodeCoverage report misses coverage for all the Swift files.

I saw your comment about no support for Swift [here](https://github.com/jonreid/XcodeCoverage/issues/33). Any Plans for doing it in future? Can you please add support for Swift files coverage.

Thanks.

**Comment by jonreid** [comment]
I don't think that Swift supports the legacy coverage format, which is needed for XcodeCoverage.
