### ISSUE TITLE
how to deal with the follow problem

### ISSUE THREAD

**Issue by lida123** [jonreid/XcodeCoverage#58]
lcov: ERROR: no valid records found in tracefile Coverage.info
Reading tracefile Coverage.info
lcov: ERROR: no valid records found in tracefile Coverage.info
Reading tracefile Coverage.info
lcov: ERROR: no valid records found in tracefile Coverage.info
Reading tracefile Coverage.info
lcov: ERROR: no valid records found in tracefile Coverage.info
Reading tracefile Coverage.info
lcov: ERROR: no valid records found in tracefile Coverage.info
Reading data file Coverage.info
genhtml: ERROR: no valid records found in tracefile Coverage.info

**Comment by jonreid** [comment]
I hope you've found your fix. Sorry I wasn't able to help.
