### ISSUE TITLE
Using xcodecoverage for the real device?

### ISSUE THREAD

**Issue by haihw** [jonreid/XcodeCoverage#59]
Hi, 
I'm able to export a nice report for test running on simulator. 
But when trying with the actual device, I always get the following errors: 
"Reading tracefile Coverage.info
lcov: ERROR: no valid records found in tracefile Coverage.info"

Any suggestion? Thank you

**Comment by jonreid** [comment]
I'm afraid I only run tests on simulator, and never on device. My scripts are designed around this approach.

Take a look at envcov.sh, lines 8-14. Maybe modifying line 11 will help?
