### ISSUE TITLE
Unable to see coverage report in XCode 11.6 with new build system.

### ISSUE THREAD

**Issue by anuragfluke** [jonreid/XcodeCoverage#60]
Unable to see coverage report in XCode 11.6 with new build system. Please see below error

11:00:18 + mkdir -p ../../build/reports/coverage_Report
11:00:18 + echo 'XcodeCoverage report generating..'
11:00:18 XcodeCoverage report generating..
11:00:18 + XcodeCoverage/getcov -o ../../build/reports/coverage_Report
11:00:18 output_dir = ../../build/reports/coverage_Report
11:00:18 /opt/jenkins/workspace/iOS_PullRequest_Unit/build/reports/coverage_Report /opt/jenkins/workspace/iOS_PullRequest_Unit/src/elektra
11:00:18 /opt/jenkins/workspace/iOS_PullRequest_Unit/src/elektra
11:00:18 Capturing coverage data from /Users/jenkins/Library/Developer/Xcode/DerivedData/elektra-dqgphexvdqtbmicihhexfohtaasc/Build/Intermediates.noindex/elektra.build/Debug_Fluke-iphonesimulator/elektra.build/Objects-normal/undefined_arch
11:00:18 Found LLVM gcov version 11.0.3, which emulates gcov version 4.2.0
11:00:18 geninfo: ERROR: cannot read /Users/jenkins/Library/Developer/Xcode/DerivedData/elektra-dqgphexvdqtbmicihhexfohtaasc/Build/Intermediates.noindex/elektra.build/Debug_Fluke-iphonesimulator/elektra.build/Objects-normal/undefined_arch!
11:00:18 lcov: ERROR: cannot read file Coverage.info!
11:00:18 Reading tracefile Coverage.info

**Comment by jonreid** [comment]
Closing as older dup of https://github.com/jonreid/XcodeCoverage/issues/63
