### ISSUE TITLE
How to  set the specified files to whitelist

### ISSUE THREAD

**Issue by ziyouzhe4** [jonreid/XcodeCoverage#61]
How to set the specified files to whitelist？ 
i want to add some files to whitelist, and only Check these files。
our project is very big. and contain so many sdks, usually  one feature we only chang A few files, i only want to check that files. don't care others files.  What should I do？
thanks, waitting for your replay!

**Comment by jonreid** [comment]
Thanks for pinging me via email.
XcodeCoverage has a way to exclude files, but doesn't have a way to specify "only include these files."
But the exclusion list can have wildcards. Hope this helps.

**Comment by ziyouzhe4** [comment]
> Thanks for pinging me via email.
> XcodeCoverage has a way to exclude files, but doesn't have a way to specify "only include these files."
> But the exclusion list can have wildcards. Hope this helps.

thanks for your replay and do you have a plan to add this function?

**Comment by jonreid** [comment]
No, since XcodeCoverage is only useful for Objective-C projects using legacy coverage settings.
